[package]
name = "th-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
th-domain = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
